[workspace]
members = [
    "familiar-architecture/familiar-contracts",
    "familiar-architecture/familiar-verify",
    "familiar-architecture/familiar-config",
    "familiar-architecture/familiar-router",
    "familiar-architecture/xtask"
]
resolver = "2"
